@startuml

title Usecase for Information system

left to right direction

actor User

rectangle Software {

    usecase (Пошук співбесідника)
    usecase (Зайти у налаштування)
    usecase (Видалити друга)
    usecase (Додати дргуа)
    usecase (Закінчити розмову)
    usecase (Заповнити обліковий запис)
    usecase (Написати повідомлення другу)
    usecase (Змінити шрифт)

   (Пошук співбесідника) .> (Заповнити обліковий запис) : include
   (Пошук співбесідника) .> (Додати друга) : extends
   (Пошук співбесідника) .> (Видалити друга) : extends
   (Пошук співбесідника) .> (Закінчити розмову) : include
   (Додати друга) .> (Написати повідомлення другу) : extends
   (Зайти у налаштування) .> (Змінити шрифт) : extends
   User -- (Зайти у налаштування)
   User -- (Пошук співбесідника)
}

@enduml
