name: DataSchemaCodeConversion
on:
  push:
    branches:
      - LW11

jobs:
  DataSchemaCodeConversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3
        
      - name: Start DataSchemaCodeConversion
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect postgres
