name: Test Cases
on: 
  push:
    branches: LW11
jobs:
  TestCases: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE/
          export CLASSPATH="./ojdbc8.jar:./"
          javac TestCase.java
      - name: Execute
        run: |
          cd $GITHUB_WORKSPACE/
          export CLASSPATH="./ojdbc8.jar:./"
          java TestCase ${{ secrets.LOGIN }} ${{ secrets.PASSWORD }} 
